### ISSUE TITLE
pip failed error

### ISSUE THREAD

**Issue by ghost** [NiBoyang/AutoDock-SS#1]
```
conda env create -f env.yaml
Retrieving notices: ...working... done
Channels:
 - conda-forge
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: done

Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: done
Executing transaction: \

    Installed package of scikit-learn can be accelerated using scikit-learn-intelex.
    More details are available here: https://intel.github.io/scikit-learn-intelex

    For example:

        $ conda install scikit-learn-intelex
        $ python -m sklearnex my_application.py

done
Installing pip dependencies: / Ran pip subprocess with arguments:
['/home/evehom/miniconda3/envs/adss/bin/python', '-m', 'pip', 'install', '-U', '-r', '/home/evehom/AutoDock-SS/condaenv.y_yxsgzx.requirements.txt', '--exists-action=b']
Pip subprocess output:

Pip subprocess error:
ERROR: Could not detect requirement name for 'git://github.com/Valdes-Tresanco-MS/AutoDockTools_py3', please specify one with #egg=your_package_name

failed

CondaEnvException: Pip failed
```

Please advise. Thank you,

Evert

**Comment by NiBoyang** [comment]
@Evert-Homan Hi Evert. Many thanks for trying AutoDock-SS. 

For this issue, I would suggest deleting the **line 143** in the yaml file `- -e git://github.com/Valdes-Tresanco-MS/AutoDockTools_py3 #autodocktools-py3==1.5.7.post1+1.g047b306`. 

And using the following command to install the AutoDockTool_py3: `pip install git+https://github.com/Valdes-Tresanco-MS/AutoDockTools_py3`.

Let me know if it works.

Best regards,
Boyang

**Comment by ghost** [comment]
Installation was successful to the extent that there were no error messages. I still need to test the code though.

Thanks for your quick reply/Evert

**Comment by NiBoyang** [comment]
No problem Evert! I'll close this issue. If you have any issue with the code, please open another issue.

Many thanks, B.N.
